# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup project
        run: make setup

      - name: Check lint
        run: make lint
